// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfgz0jZLMnSyoKvtLwkiZmggcgpk0KbX8',
    appId: '1:236484354616:web:fea9bf999dcbbee01dbccd',
    messagingSenderId: '236484354616',
    projectId: 'suxoy-zakon',
    authDomain: 'suxoy-zakon.firebaseapp.com',
    storageBucket: 'suxoy-zakon.appspot.com',
    measurementId: 'G-72YNWK8K1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWiKbBNaAyReTGFjxTkwaNSpMPDe_JPgI',
    appId: '1:236484354616:android:1b750d078645169c1dbccd',
    messagingSenderId: '236484354616',
    projectId: 'suxoy-zakon',
    storageBucket: 'suxoy-zakon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSMT5lDGO5K6dEA-ya6YQ90h_aJKs-Gw',
    appId: '1:236484354616:ios:95d4eb61268b4fb71dbccd',
    messagingSenderId: '236484354616',
    projectId: 'suxoy-zakon',
    storageBucket: 'suxoy-zakon.appspot.com',
    iosClientId: '236484354616-pvua8bu0licur7hhp6gefj31b8n3nq7v.apps.googleusercontent.com',
    iosBundleId: 'ru.mq.suxoyZakon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLSMT5lDGO5K6dEA-ya6YQ90h_aJKs-Gw',
    appId: '1:236484354616:ios:cb24172a2a45610b1dbccd',
    messagingSenderId: '236484354616',
    projectId: 'suxoy-zakon',
    storageBucket: 'suxoy-zakon.appspot.com',
    iosClientId: '236484354616-nsbc7r260878a9jt3cu8a7ep4pv2ehfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.suxoyZakon',
  );
}
